In [2]:
import numpy as np

In [3]:
print (np.__version__)

1.16.4


In [4]:
my_list = [-17,0,4,5,9] # comma is the separator 
my_nump_array = np.array ( my_list ) # pass the array to this list 

my_nump_array


array([-17,   0,   4,   5,   9])

In [5]:
my_nump_array * 10 

array([-170,    0,   40,   50,   90])

In [6]:
my_tuple = (4,-5 , 7+2j)
np.array(my_tuple)  # all numbers are promoted to their highest type like Xomplex number is the highest.
                    # since complex can accomodate all hence this is teh highest form. 

array([ 4.+0.j, -5.+0.j,  7.+2.j])

### Difference between Python and Numpy Data Structures 

In [7]:
my_tuple * 2  # Each element is multiplied by 6 

(4, -5, (7+2j), 4, -5, (7+2j))

In [8]:
np.array(my_tuple) * 6 

array([ 24. +0.j, -30. +0.j,  42.+12.j])

## Intrinsic Array creationg using Numpy functions 

In [9]:
np.arange(7)   # Create an array with a range of integers 
                # start with zero and one less than the "stop"

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
np.arange( 10, 23 )  # Create an array with a range of integers starting with zero 
                # start with zero and one less than the "stop"

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [11]:
len (np.arange( 10, 23 ))

13

In [12]:
my_arange_array =np.arange( 10, 23 ) 
my_arange_array.size

13

In [13]:
np.arange( 10, 23 , 5 )  # Here 5 is the step. 
                        # note that numpy includes the starts values. Hence 10 is teh first element

array([10, 15, 20])

In [14]:
np.arange( 10, 27, 5  ) 

array([10, 15, 20, 25])

In [15]:
np.arange( 10, 23 , step = 5 ) 

array([10, 15, 20])

# Other Functions : linspace , zeros, ones & data types 

In [16]:
# linspace creates an array which is linearly spaced . Has 2 to 6 elements 
# start , stop and numbers of elements to put 
# linspace uses a closed interval unlike arange which uses a closed interval 



In [17]:
np.linspace ( 2, 6  ,10 )

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [18]:
my_linspace = np.linspace(5,15,9, retstep = True) # retstep will return the step size along with the array 

In [19]:
my_linspace


(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [20]:
my_linspace[1]

1.25

### zeros 

In [21]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

### Ones 

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.zeros((5,4)) # each zero is of type floating by default . Notice two [] brackets 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.zeros (( 5,4,3))  # 5 total rows, 4 groups, 3 columns 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.zeros(11 , dtype = 'int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
my_vector = np.array ([-17,8,66,28,90])

In [27]:
my_vector

array([-17,   8,  66,  28,  90])

In [28]:
my_vector[0]

-17

In [29]:
my_vector[-3]

66

In [30]:
my_vector.size

5

### Two dim array


In [31]:
my_array = np.arange(35)

In [32]:
my_array  # note that this create an array with one row and 35 cols (1 * 35 ) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [33]:
my_array.shape = (7,5 )
my_array   # this gives shape of 7 rows and 5 cols to this array created above 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [34]:
my_array[2]

array([10, 11, 12, 13, 14])

In [35]:
 my_array [2,3] # my_array [ row , column ]

13

In [36]:
# better define the row n column number and then call it 
row = 5 
column = 2 
my_array [row, column ]

27

### Three dim

In [37]:
my_3dim_array = np.arange(70)
my_3dim_array.shape = (2,7,5)
my_3dim_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [38]:
my_3dim_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [39]:
my_3dim_array[1,3]

array([50, 51, 52, 53, 54])

In [40]:
my_3dim_array[1,3,2]

52

In [41]:
my_3dim_array[1,3,2] = 1151
my_3dim_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1151,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

In [42]:
my_3dim_array = np.arange(70)
my_3dim_array.shape = ( 2,7,5)
my_3dim_array


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [ ]:
#Numpy requirs that the arrays must be compatible before broadcasting. meaning, either the shapes should be the same 
# or one of the size should be zero

In [43]:
my_3dim_array.shape

(2, 7, 5)

In [44]:
my_3dim_array.ndim

3

In [45]:
my_3dim_array.size

70

In [47]:
my_3dim_array.dtype

dtype('int64')

In [48]:
left = np.arange(6).reshape((2,3))
right = np.arange(15).reshape(3,5)

In [49]:
np.dot(left,right)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along the axes

In [50]:
my_3dim_array.sum()

2415

In [51]:
my_3dim_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [52]:
my_3dim_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [53]:
my_3dim_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [ ]:
#For a matrix : 2 * 7 * 5 Note. 
#    When you do sum across (axis=0) ==> result = array of 7 by 5. You remove 2 here 
#    When you do sum across (axis=1) ==> result = array of 2 by 5. You remove 7 here 
#    When you do sum across (axis=2) ==> result = array of 2 by 7. You remove 5 here 

### Creating Structured Array

In [ ]:
#Numpy supports complex data structure that are not only numbersbut also a mix of different types like float , string etc 
#hence called strcutured array 

In [54]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'),('age','i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [55]:
people_array = np.zeros((4), dtype = person_data_def)
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [59]:
people_array [3]=('Delta',73,205,34)
people_array [0]=('Alpha',65,112,23)

people_array 

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [61]:
ages = people_array['age']
ages/2

array([11.5,  0. ,  0. , 17. ])

# New Chapter

### Plotting using PlotLib